### ISSUE TITLE
Shimboot not boots via sd card

### ISSUE THREAD

**Issue by Project01X** [ading2210/shimboot#44]
**Describe the bug**
When creating bootable media using an SD card instead of a pendrive and placing it on the Chromebook (Lenovo 100e gen 3 version amd codename zork:vilboz) I receive the following error:

> EROR: Factory installation aborted.
> To debug, add [cross_debug] to your command line.

**To Reproduce**
1. Find the board name of your Chromebook. You can search for the model name on [chrome100.dev](https://chrome100.dev/).
2. Download the correct prebuilt image according your chromebook board (chromebook board name is `zork` in my case).
3. Flash downloaded image into sd card using dd, here is the command (assuming that sd card is on usb converter as `/dev/sdd`):
        `sudo dd if=shimboot_zork.bin of=/dev/sdd bs=1M status=progress`
4. Insert sd card on chromebook and boot up following this [instructions](https://sh1mmer.me/) (see the "Executing on Chromebook" section)
5. See the error

NOTE 1: I repeated the same steps using a pendrive instead of an SD card and the booting happened normally.
NOTE 2: After making the SD card bootable, I tested it in two cases:
               **The first** as described in the previous steps: inserting the SD card directly into the Chromebook nd getting the mentioned error.
               **The second:** I inserted the sd card into the converter to usb and connected it to chrome, the shimboot worked as expected, the boot was successful and I was able to enter debian.

**Expected behavior**
When inserting the SD card into the Chromebook and carrying out the correct procedures to run shimboot, the disk boot selection interface to enter Debian should be loaded normally, as well as the Linux-based system itself.

**Screenshots / Photos**
Here is an error screenshot
![20240721_171849](https://github.com/user-attachments/assets/cdb305b6-9061-48ca-8fcf-24021a54c0cc)

**Target Chrome OS Device (please complete the following information):**
 - Board Name (zork)
 - Device Name (vilboz)
 - Shimboot version (v1.1.1)

**Comment by ading2210** [comment]
I believe this is a bug with the shim initramfs itself, so there's nothing you can do here. Because the initramfs is built into the shim kernel, and the shim kernel is signed, there is no way to fix this.

**Comment by karaage-2** [comment]
I am facing the exact same issue with my lenovo 300e gen3 chromebook (zork,vilboz360).

I ran "fdisk -l" from the shimboot shell(the option "s") with and without the sd card.

The shimboot usb(working fine with gnome) that i used to run fdisk was mounted at /dev/sda.
Without the sd card it shows that there is a device at /dev/mmcblk1 which should be the eMMC storage of the chromebook.
With the sd card it shows that there is another disk at /dev/mmcblk0 which should be the sd card.

I am very new and I don't even really know how linux usually boots but mmcblk1 should be the usual place where sd cards are 
mounted so maybe shimboot or smth else is trying to boot linux from our emmc storages.In that case I guess we just need to rewrite mmcblk1 to mmcblk0.

Maybe this bug won't be fixed by vk6 but I will leave this info here for people who is enough knowledged and trying to use shimboot on a lenovo chromebook.
